apiVersion: apps/v1
kind: Deployment
metadata:
  name: primacy-cms-api
  namespace: primacy-care
  labels:
    app: primacy-cms
    component: api
    version: "2.0.0"
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: primacy-cms
      component: api
  template:
    metadata:
      labels:
        app: primacy-cms
        component: api
        version: "2.0.0"
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/actuator/prometheus"
        prometheus.io/port: "5000"
    spec:
      serviceAccountName: primacy-cms
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
      containers:
      - name: cms-api
        image: primacycare/cms-api:2.0.0
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
          name: http
          protocol: TCP
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "production"
        - name: SERVER_PORT
          value: "5000"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: primacy-cms-secrets
              key: database-url
        - name: KEYCLOAK_ISSUER_URI
          value: "https://auth.primacycare.com.au/realms/primacy-care"
        - name: KEYCLOAK_JWK_SET_URI
          value: "https://auth.primacycare.com.au/realms/primacy-care/protocol/openid-connect/certs"
        - name: CORS_ORIGINS
          value: "https://app.primacycare.com.au"
        - name: GCS_BUCKET
          value: "primacy-cms-production"
        - name: XERO_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: primacy-cms-secrets
              key: xero-client-id
        - name: XERO_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: primacy-cms-secrets
              key: xero-client-secret
        - name: SENDGRID_API_KEY
          valueFrom:
            secretKeyRef:
              name: primacy-cms-secrets
              key: sendgrid-api-key
        - name: ANTHROPIC_API_KEY
          valueFrom:
            secretKeyRef:
              name: primacy-cms-secrets
              key: anthropic-api-key
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 5000
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        volumeMounts:
        - name: app-logs
          mountPath: /app/logs
        - name: tmp
          mountPath: /tmp
      volumes:
      - name: app-logs
        emptyDir: {}
      - name: tmp
        emptyDir: {}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - primacy-cms
              topologyKey: kubernetes.io/hostname
---
apiVersion: v1
kind: Service
metadata:
  name: primacy-cms-api
  namespace: primacy-care
  labels:
    app: primacy-cms
    component: api
spec:
  type: ClusterIP
  ports:
  - port: 5000
    targetPort: 5000
    protocol: TCP
    name: http
  selector:
    app: primacy-cms
    component: api
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: primacy-cms-api
  namespace: primacy-care
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: primacy-cms-api
  minReplicas: 3
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: primacy-cms-api
  namespace: primacy-care
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: primacy-cms
      component: api
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: primacy-cms-api
  namespace: primacy-care
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "60"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "60"
    nginx.ingress.kubernetes.io/rate-limit: "100"
    nginx.ingress.kubernetes.io/limit-connections: "10"
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-origin: "https://app.primacycare.com.au"
    nginx.ingress.kubernetes.io/cors-allow-methods: "GET, POST, PUT, DELETE, OPTIONS, PATCH"
    nginx.ingress.kubernetes.io/cors-allow-headers: "Authorization, Content-Type, X-Correlation-ID"
spec:
  tls:
  - hosts:
    - api.primacycare.com.au
    secretName: primacy-cms-api-tls
  rules:
  - host: api.primacycare.com.au
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: primacy-cms-api
            port:
              number: 5000